controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:  
    joints:
      - left_wheel_leg_joint
      - right_wheel_leg_joint
      - left_wheel_back_leg_joint
      - right_wheel_back_leg_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
  


velocity_controller:
  ros__parameters:  
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - wheel_back_right_joint
      - wheel_back_left_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


joint_state_broadcaster:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true


    

